<?php
add_action('acf/include_field_types', 'include_custom_field_types');

function include_custom_field_types( $version ) {
	include_once('color-radio.php');
	include_once('day-picker.php');
}

if (function_exists("register_field_group")) {
	include_once('register_fields_helpers.php');
	include_once('register_fields_helpers_widgets.php');
	include_once('register_fields_term_top_widgets.php');
	include_once('register_fields_term_bottom_widgets.php');
//	include_once('register_fields_footer_widgets.php');
	include_once('register_fields_adverts.php');
	include_once('register_fields_home_page.php');
	include_once('register_fields_houses.php');
	include_once('register_fields_options.php');
	include_once('register_fields_seasonal.php');
	include_once('register_fields_availability.php');
	include_once('register_fields_special_offers.php');
	include_once('register_fields_suppliers.php');
	include_once('register_fields_taxonomies.php');
}


if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_59494e117c0e7',
	'title' => 'Added Discount Logic',
	'fields' => array (
		array (
			'key' => 'field_59494ef53a4be',
			'label' => 'Discount Logic',
			'name' => 'discount_logic',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Add Discount Logic',
			'min' => '',
			'max' => '',
			'layouts' => array (
				array (
					'key' => '59494ef9d826d',
					'name' => 'add_discount_logic',
					'label' => 'Add Discount Logic',
					'display' => 'table',
					'sub_fields' => array (
						array (
							'key' => 'field_594953da38776',
							'label' => 'Logic Type',
							'name' => 'logic_type',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'set' => 'Set Dates',
								'rolling' => 'Rollling Days',
							),
							'default_value' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'disabled' => 0,
							'readonly' => 0,
						),
						array (
							'key' => 'field_59494f263a4c0',
							'label' => 'No Rolling Days',
							'name' => 'no_rolling_days',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_594953da38776',
										'operator' => '==',
										'value' => 'rolling',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => '',
							'max' => '',
							'step' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_5949551238777',
							'label' => 'From',
							'name' => 'from',
							'type' => 'date_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_594953da38776',
										'operator' => '==',
										'value' => 'set',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'display_format' => 'd/m/Y',
							'return_format' => 'd/m/Y',
							'first_day' => 1,
						),
						array (
							'key' => 'field_5949553138778',
							'label' => 'To',
							'name' => 'to',
							'type' => 'date_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_594953da38776',
										'operator' => '==',
										'value' => 'set',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'display_format' => 'd/m/Y',
							'return_format' => 'd/m/Y',
							'first_day' => 1,
						),
						array (
							'key' => 'field_59494f0b3a4bf',
							'label' => 'Discount',
							'name' => 'discount',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '%',
							'min' => '',
							'max' => '',
							'step' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'houses',
			)
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_5b25369d19dd5',
	'title' => 'Lower Widgets',
	'fields' => array (
		array (
			'key' => 'field_5b2536ad9239b',
			'label' => 'Lower Widgets',
			'name' => 'lower_widgets',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Add Lower Widget',
			'min' => '',
			'max' => '',
			'layouts' => array (
				array (
					'key' => '5b2536b5aafe5',
					'name' => 'standard',
					'label' => 'Standard',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_5b2537559239f',
							'label' => 'Title',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_5b253774923a0',
							'label' => 'Sub Title',
							'name' => 'sub_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_5b2537a1923a1',
							'label' => 'Main Body',
							'name' => 'main_body',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'wpautop',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_5b2537d3923a2',
							'label' => 'Gallery',
							'name' => 'gallery',
							'type' => 'gallery',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'min' => '',
							'max' => '',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_5b2537f5923a3',
							'label' => 'Layout',
							'name' => 'layout',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'imgleft' => 'Image left',
								'imgright' => 'Image right',
								'galleryleft' => 'Gallery left',
								'galleryright' => 'Gallery right',
								'largeimg' => 'Large image',
								'text' => 'Text only',
								'fourimage' => 'Four images only',
							),
							'default_value' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'disabled' => 0,
							'readonly' => 0,
						),
						array (
							'key' => 'field_5b253812923a4',
							'label' => 'Colour',
							'name' => 'color_scheme',
							'type' => 'color_radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'choices' => kat_colors_array('all'),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '5b3e47d0f35a5',
					'name' => 'image_set',
					'label' => 'Navigation Image Set',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_5b3e47e8f35a6',
							'label' => 'Style',
							'name' => 'surround',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'fill' => 'Full-size box',
								'half' => 'Half-size box',
								'image' => 'Full-size image only',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => '',
							'layout' => 'vertical',
						),
						array (
							'key' => 'field_5b3e4804f35a7',
							'label' => 'Background Colour',
							'name' => 'color_scheme',
							'type' => 'color_radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'choices' => kat_colors_array('all'),
						),
						array (
							'key' => 'field_5b3e481bf35a8',
							'label' => 'Navigation Image Set',
							'name' => 'imageset',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'min' => '',
							'max' => '',
							'layout' => 'table',
							'button_label' => 'Add Row',
							'sub_fields' => array (
								array (
									'key' => 'field_5b3e4b5772d65',
									'label' => 'Set',
									'name' => 'row',
									'type' => 'repeater',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'min' => '',
									'max' => '',
									'layout' => 'table',
									'button_label' => 'Add Row',
									'sub_fields' => array (
										array (
											'key' => 'field_5b3e4b6372d66',
											'label' => 'Image',
											'name' => 'image',
											'type' => 'image',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'return_format' => 'array',
											'preview_size' => 'thumbnail',
											'library' => 'all',
											'min_width' => '',
											'min_height' => '',
											'min_size' => '',
											'max_width' => '',
											'max_height' => '',
											'max_size' => '',
											'mime_types' => '',
										),
										array (
											'key' => 'field_5b3e4b6c72d67',
											'label' => 'Title',
											'name' => 'title_text',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
											'readonly' => 0,
											'disabled' => 0,
										),
										array (
											'key' => 'field_5b3e4b7972d68',
											'label' => 'Subtitle',
											'name' => 'subtitle_text',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
											'readonly' => 0,
											'disabled' => 0,
										),
										array (
											'key' => 'field_5b3e4b8072d69',
											'label' => 'Subtext',
											'name' => 'subtext',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
											'readonly' => 0,
											'disabled' => 0,
										),
										array (
											'key' => 'field_5b3e4b8572d6a',
											'label' => 'Colour',
											'name' => 'colour_scheme',
											'type' => 'color_radio',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'choices' => kat_colors_array('all'),
										),
										array (
											'key' => 'field_5b3e4b9172d6b',
											'label' => 'Custom URL',
											'name' => 'set_custom',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
											'readonly' => 0,
											'disabled' => 0,
										),
									),
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'suppliers',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'houses',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'seasonal',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'availability',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;

?>